spring:
  # 配置数据源信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      # 设置默认的数据源或者数据源组 默认值即为master
      primary: master
      # 严格匹配数据源 默认false true表示未匹配到指定数据源时抛出异常 false使用默认数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=UTF-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: java
        slave_1:
          url: jdbc:mysql://localhost:3306/mybatis_plus_1?characterEncoding=UTF-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: java
